## Lab | Handling Data Imbalance in Classification Models

- Import the required libraries and modules that you would need.
- Read that data into Python and call the dataframe churnData.
- Check the datatypes of all the columns in the data. You would see that the column TotalCharges is object type. Convert this column into numeric type using pd.to_numeric function.
- Check for null values in the dataframe. Replace the null values.
- Use the following features: tenure, SeniorCitizen, MonthlyCharges and TotalCharges:
- Scale the features either by using normalizer or a standard scaler.
- Split the data into a training set and a test set.
- Fit a logistic regression model on the training data.
- Check the accuracy on the test data.
- Note: So far we have not balanced the data.

Managing imbalance in the dataset

- Check for the imbalance.
- Use the resampling strategies used in class for upsampling and downsampling to create a balance between the two classes.
- Each time fit the model and see how the accuracy of the model is.

In [1]:
#Import the required libraries and modules that you would need
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import preprocessing
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

In [183]:
#Read that data into Python and call the dataframe churnData
churnData=pd.read_csv('Customer-churn.csv')
churnData

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

     OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0                No          Yes               No          No          No   
1               Yes           No              Yes          No          No   
2               Yes          Yes               No          No          No   
3               Yes           No              Yes         Yes          No   
4                No           No               No          No          No   
...             ...          ...              ...         ...         ...   
7038            Yes           No              Yes         Yes         Yes   
7039             No          Yes              Yes          No         Yes   
7040            Yes           No               No          No          No   
7041             No           No               No          No          No   
7042            Yes           No              Yes         Yes         Yes   

     StreamingMovies        Contract  MonthlyCharges TotalCharges Churn  
0                 No  Month-to-month           29.85        29.85    No  
1                 No        One year           56.95       1889.5    No  
2                 No  Month-to-month           53.85       108.15   Yes  
3                 No        One year           42.30      1840.75    No  
4                 No  Month-to-month           70.70       151.65   Yes  
...              ...             ...             ...          ...   ...  
7038             Yes        One year           84.80       1990.5    No  
7039             Yes        One year          103.20       7362.9    No  
7040              No  Month-to-month           29.60       346.45    No  
7041              No  Month-to-month           74.40        306.6   Yes  
7042             Yes        Two year          105.65       6844.5    No  

[7043 rows x 16 columns]

In [184]:
#Check the datatypes of all the columns in the data. You would see that the column TotalCharges is object type. Convert this column into numeric type using pd.to_numeric function
churnData.dtypes


gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [185]:
churnData['TotalCharges']=pd.to_numeric(churnData['TotalCharges'], errors='coerce')
churnData.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [186]:
#Check for null values in the dataframe. Replace the null values
churnData.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [187]:
churnData['TotalCharges'] =churnData['TotalCharges'].fillna(churnData['TotalCharges'].mean())
churnData.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [188]:
#Use the following features: tenure, SeniorCitizen, MonthlyCharges and TotalCharges: Scale the features either by using normalizer or a standard scaler
churn_scale= churnData[['tenure', 'SeniorCitizen','MonthlyCharges', 'TotalCharges']]
churn_scale.head()


tenure  SeniorCitizen  MonthlyCharges  TotalCharges
0       1              0           29.85         29.85
1      34              0           56.95       1889.50
2       2              0           53.85        108.15
3      45              0           42.30       1840.75
4       2              0           70.70        151.65

In [189]:
scale= StandardScaler()
churn_stan=scale.fit_transform(churn_scale)
churn_stan=pd.DataFrame(churn_stan)
churn_stan.head()

0         1         2         3
0 -1.277445 -0.439916 -1.160323 -0.994971
1  0.066327 -0.439916 -0.259629 -0.173876
2 -1.236724 -0.439916 -0.362660 -0.960399
3  0.514251 -0.439916 -0.746535 -0.195400
4 -1.236724 -0.439916  0.197365 -0.941193

In [190]:
#Split the data into a training set and a test set
X=churn_stan
y=churnData['Churn'] 
y

0        No
1        No
2       Yes
3        No
4       Yes
       ... 
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object

In [191]:
#Fit a logistic regression model on the training data
y=pd.DataFrame(y)
y = y.apply(preprocessing.LabelEncoder().fit_transform)
y


Churn
0         0
1         0
2         1
3         0
4         1
...     ...
7038      0
7039      0
7040      0
7041      1
7042      0

[7043 rows x 1 columns]

In [192]:
# Veamos la de sklearn, en esta no es necesario cambiar el \"y\" a numerico, en el caso de la regresion logistica con stats model, si
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=50)
model = LogisticRegression( random_state=50)

In [193]:
model.fit(X_train, y_train)

LogisticRegression(random_state=50)

In [194]:
model.classes_


array([0, 1])

In [195]:
model.coef_

array([[-1.52965513,  0.207177  ,  0.90007558,  0.18337523]])

In [196]:
model.intercept_

array([-1.47174477])

In [197]:
model.score(X_train,y_train)

0.7905573304934327

In [198]:
##Check the accuracy on the test data.
model.score(X_test,y_test)

0.7849538679914834

In [199]:
#Check for the imbalance
churnData['Churn'].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [200]:
#Use the resampling strategies used in class for upsampling and downsampling to create a balance between the two classes.

smote_over= SMOTE()
Xsmote, ysmote =smote_over.fit_resample(X,y)

In [201]:
ysmote.value_counts()

Churn
0        5174
1        5174
dtype: int64

In [202]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(Xsmote, ysmote, test_size=0.20, random_state=50)
modelsm = LogisticRegression( random_state=50)
modelsm.fit(X_train2, y_train2)

LogisticRegression(random_state=50)

In [203]:
modelsm.score(X_train2, y_train2)

0.7370137714423773

In [204]:
modelsm.score(X_test2, y_test2)

0.7328502415458937

In [205]:
#upsampling 

In [206]:
oversample= RandomOverSampler(sampling_strategy=0.5)

In [207]:
X_over, y_over=oversample.fit_resample(X,y)

In [208]:
y_over.value_counts()

Churn
0        5174
1        2587
dtype: int64

In [209]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X_over, y_over, test_size=0.20, random_state=50)
modelos = LogisticRegression(random_state=50)
modelos.fit(X_train3, y_train3)

LogisticRegression(random_state=50)

In [210]:
modelos.score(X_train3, y_train3)

0.7583762886597938

In [211]:
modelos.score(X_test3, y_test3)

0.7405022537025112

In [212]:
#undersampling

In [213]:
undersample= RandomUnderSampler(sampling_strategy='majority')

In [214]:
X_under, y_under=undersample.fit_resample(X,y)

In [215]:
y_under.value_counts()

Churn
0        1869
1        1869
dtype: int64

In [216]:
X_train4, X_test4, y_train4, y_test4 = train_test_split(X_under, y_under, test_size=0.20, random_state=50)
modelund = LogisticRegression(random_state=50)
modelund.fit(X_train4, y_train4)

LogisticRegression(random_state=50)

In [217]:
modelund.score(X_train4, y_train4)

0.7411371237458194

In [218]:
modelund.score(X_test4, y_test4)

0.75

In [219]:
 modelos = pd.DataFrame({
       'Model': ['Logistic Regression', 'Logistic Regression Random OverS', 'Logistic Regression Random UnderS', 'Logistic Regression Over S con SMOTE'],
       'Score': [model.score(X_train,y_train), modelos.score(X_train3,y_train3), modelund.score(X_train4,y_train4), modelsm.score(X_train2,y_train2)] })

In [220]:
 modelos

Model     Score
0                   Logistic Regression  0.790557
1      Logistic Regression Random OverS  0.758376
2     Logistic Regression Random UnderS  0.741137
3  Logistic Regression Over S con SMOTE  0.737014